[build]
    publish = "dist/user-activity"
    command = "ng build --configuration production"
    functions = "./netlify/functions"
    targetPort = 8888
[[redirects]]
    from = "/*"
    to   = "/index.html"
    status = 200
    targetPort = 8888